### ISSUE TITLE
Code for ReMixMatch?

### ISSUE THREAD

**Issue by pm25** [ZJUJeffLai/SAW_SSL#2]
Hi. Thanks for the great work here.
In the paper, you presented results of experiments with ReMixMatch. However, I couldn't find the code for ReMixMatch in this repository, only the code for FixMatch. Could you provide the source code of ReMixMatch + SAW so that I can reproduce the results? Thanks!

**Comment by ZJUJeffLai** [comment]
Hi, thanks for your interest. We are still wrapping up the codes for ReMixMatch and will let you know once we finish that.

**Comment by PM25** [comment]
Is there an expected date for the release of the code?

**Comment by ZJUJeffLai** [comment]
Hi, I just fixed my git and uploaded it here: 
https://github.com/ZJUJeffLai/SAW_SSL/blob/main/train_remix_cifar10.py

**Comment by pm25** [comment]
Thanks so much for responding so quickly!
