### ISSUE TITLE
Inconsistent result on baseline Fixmatch

### ISSUE THREAD

**Issue by butcher1226** [ZJUJeffLai/SAW_SSL#3]
Sorry to bother you, but when reproducing your code, I can't get the same results mentioned in your paper. Even when removing the adaptive weighting, just run Fixmatch, I got the mean acc 55.06, which is much worse than 60.1 in your paper, could you explain why? Thank you.

**Comment by butcher1226** [comment]
The setting is CIFAR100, imb_ratio_l 10, imb_ratiol_u 10, num_max 150

**Comment by ZJUJeffLai** [comment]
Hello, thanks for your message. Our codes are based on this repo: https://github.com/bbuing9/DARP 
Could you run this repo and see if you can get 60.1? Meanwhile, I'll run my Repo on my side to see the issues. I may not upload the right version of the scripts. Sorry about that.
